homeassistant:
  name: Home
  unit_system: metric

lovelace:
  mode: yaml
  resources:
    - url: /local/slider-entity-row.js?v=17.0.0
      type: js
  dashboards:
    my-dashboard:
      mode: yaml
      title: My Dashboard
      filename: my_dashboard.yaml
      show_in_sidebar: false
      require_admin: false

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder: 
  db_url: !secret db_url

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

light: !include entities/lights.yaml

input_number:
  light_step:
    name: "Step the lights this much"
    initial: 20
    min: 1
    max: 64
    step: 1

  light_minimum:
    name: "No dimmer than this"
    initial: 5
    min: 1
    max: 255
    step: 1

  light_maximum:
    name: "No brighter than this"
    initial: 255
    min: 50
    max: 255
    step: 1

  light_delay_ms:
    name: "Step the lights this often (ms)"
    initial: 500
    min: 100
    max: 5000
    step: 100

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: memory_use_percent
      - type: memory_use
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

google_assistant: !include google_assistant.yaml

automation kitchen_table_lights_from_yaml: !include automations/kitchen_table_lights.yaml

media_player:
  - platform: nad
    type: TCP
    host: 192.168.1.13
    port: 23
    name: NAD Receiver
    min_volume: -60
    max_volume: -30
    sources:
      1: "Stream"
      2: "Wireless"
      3: "TV"
      4: "Phono"
      5: "Coax1"
      6: "Coax2"
      7: "Opt1"
      8: "Opt2"
      
